#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Definir el número del botón que activará el ciclo
#define BOTON_INICIO Btn5U

// Función para configurar los encoders
void configurarEncoders() {
    SensorType[rightEncoder] = sensorQuadEncoder;
    SensorType[leftEncoder] = sensorQuadEncoder;
}

// Función para avanzar una distancia específica en pulsaciones de encoder
void avanzar(int pulsaciones) {
    SensorValue[rightEncoder] = 0;
    SensorValue[leftEncoder] = 0;

    while (abs(SensorValue[leftEncoder]) < pulsaciones) {
        if (SensorValue[leftEncoder] > SensorValue[rightEncoder]) {
            motor[rightMotor] = 70; // Motor derecho
            motor[leftMotor] = 50; // Motor izquierdo
        } else if (SensorValue[rightEncoder] > SensorValue[leftEncoder]) {
            motor[rightMotor] = 50; // Motor derecho
            motor[leftMotor] = 70; // Motor izquierdo
        } else {
            motor[rightMotor] = 70; // Motor derecho
            motor[leftMotor] = 70; // Motor izquierdo
        }
    }

    motor[rightMotor] = 0;
    motor[leftMotor] = 0;
}

int pulsosNecesarios(float distRequerida) {
    float circunferencia = 10.16 * PI; // Circunferencia de la rueda en centímetros
    float pulso = 360; // Pulsos por revolución del encoder
    float distXpulso = circunferencia / pulso; // Calcula la distancia por pulso
    int numPulsosRequeridos = distRequerida / distXpulso; // Calcula el número de pulsos requeridos
    return numPulsosRequeridos;
}

// Función para girar a la derecha exactamente 90 grados
void girarDerecha90() {
    int pulsaciones = pulsosNecesarios(10.16 * PI / 2); // Calcula el número de pulsaciones para girar 90 grados (pi * diametro_rueda / 4)
    SensorValue[rightEncoder] = 0;
    SensorValue[leftEncoder] = 0;

    while (abs(SensorValue[rightEncoder]) < pulsaciones) {
        motor[rightMotor] = -50; // Motor derecho hacia atrás
        motor[leftMotor] = 70; // Motor izquierdo hacia adelante
    }

    motor[rightMotor] = 0;
    motor[leftMotor] = 0;
}

// Función para girar a la derecha exactamente 90 grados
void girarDerecha902() {
    int pulsaciones = pulsosNecesarios(10.16 * PI / 2); // Calcula el número de pulsaciones para girar 90 grados (pi * diametro_rueda / 4)
    SensorValue[rightEncoder] = 0;
    SensorValue[leftEncoder] = 0;

    while (abs(SensorValue[rightEncoder]) < pulsaciones) {
        motor[rightMotor] = -50; // Motor derecho hacia atrás
        motor[leftMotor] = 80; // Motor izquierdo hacia adelante
    }

    motor[rightMotor] = 0;
    motor[leftMotor] = 0;
}

// Función para girar a la izquierda exactamente 90 grados
void girarIzquierda90() {
    int pulsaciones = pulsosNecesarios(10.16 * PI / 2); // Calcula el número de pulsaciones para girar 90 grados (pi * diametro_rueda / 4)
    SensorValue[rightEncoder] = 0;
    SensorValue[leftEncoder] = 0;

    while (abs(SensorValue[leftEncoder]) < pulsaciones) {
        motor[rightMotor] = 70; // Motor derecho hacia adelante
        motor[leftMotor] = -50; // Motor izquierdo hacia atrás
    }

    motor[rightMotor] = 0;
    motor[leftMotor] = 0;
}
// Función para esperar hasta que se presione el botón de inicio
void esperarInicio() {
    while (true) {
        if (vexRT[BOTON_INICIO] == 1) {
            break; // Salir del ciclo si se presiona el botón de inicio
        }
        wait1Msec(10); // Esperar un breve período antes de verificar de nuevo
    }
}

task main() {
    while (true) {
        // Esperar hasta que se presione el botón de inicio
        //esperarInicio();

        // Ejecutar el código principal
        wait1Msec(2000);
        configurarEncoders();
        int pulso1 = pulsosNecesarios(160.0);
        int pulso2 = pulsosNecesarios(110.0);// Ejemplo con avance de 100 centímetros
        int pulso3 = pulsosNecesarios(80.0);
        avanzar(pulso1);
        girarIzquierda90();
        avanzar(pulso2);
        girarDerecha90();
        avanzar(pulso3);
        girarDerecha90();
        avanzar(pulso2);
        girarDerecha90();
        avanzar(pulso1+pulso3);


    }
}
